language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - echo 'Build starts...'
  - mkdir dist
  - npm run prod
  - ls dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
